library(PharmacoGx)
downloadPSet("GDSC_2013")
downloadPSet("CCLE_2013")
load("~/capsule/code/PSets/CCLE_2013.RData")
load("~/capsule/code/PSets/GDSC_2013.RData")
intersectPSet(c(CCLE, GDSC), intersectOn = c("drugs", "cell.lines"))
